apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: helpdesk-infra
  labels:
    app: mongodb
    app.kubernetes.io/part-of: helpdesk-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
      - name: fix-mongodb-lock
        image: busybox:1.35
        command: ['sh', '-c', 'rm -f /data/db/mongod.lock || true']
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      containers:
      - name: mongodb
        image: mongo:7.0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: mongo-password
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        # Упрощенные health checks
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc