apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: helpdesk-infra
  labels:
    app: mongodb
    app.kubernetes.io/part-of: helpdesk-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: mongo-password
        - name: MONGO_INITDB_DATABASE
          value: "helpdesk"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        # Правильные health check пробы
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - 'mongosh --username admin --password "$MONGO_INITDB_ROOT_PASSWORD" --eval "db.adminCommand(\"ping\")" --quiet'
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - 'mongosh --username admin --password "$MONGO_INITDB_ROOT_PASSWORD" --eval "db.adminCommand(\"ping\")" --quiet'
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc