apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: helpdesk-infra
  labels:
    app: mongodb
    app.kubernetes.io/part-of: helpdesk-infra
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb