apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: helpdesk-infra
data:
  init.sql: |
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO helpdesk_user;