apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: helpdesk-infra
  labels:
    app: postgres
    app.kubernetes.io/part-of: helpdesk-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "helpdesk"
        - name: POSTGRES_USER
          value: "helpdesk_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "pg_isready -U helpdesk_user -d helpdesk"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "pg_isready -U helpdesk_user -d helpdesk"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: helpdesk-infra
  labels:
    app: postgres
    app.kubernetes.io/part-of: helpdesk-infra
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres