apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpdesk-infra

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres/pvc.yaml
  - postgres/configmap.yaml
  - postgres/deployment.yaml
  - mongodb/pvc.yaml
  - mongodb/deployment.yaml
  - redis/pvc.yaml
  - redis/deployment.yaml
  - minio/pvc.yaml
  - minio/deployment.yaml
  - keycloak/configmap.yaml
  - keycloak/deployment.yaml

# Заменяем пароли из .env файла
secretGenerator:
- name: helpdesk-secrets
  behavior: replace
  literals:
  - postgres-password=postgres_secure_123
  - mongo-password=mongo_secure_123  
  - redis-password=redis_secure_123
  - minio-password=minio_secure_123
  - keycloak-password=keycloak_secure_123